### ISSUE TITLE
Ошибка в расчете урона при значении защиты героя = "2"

### ISSUE THREAD

**Issue by a13x59** [rudnovd/heroes3-damage-calculator#2]
Если значение защиты у героя равно 2, то наблюдается странное поведение в счетчике урона (непропорциональное уменьшение).

Defense = 1, Damage: 25 — 63 (~ 44)
![image](https://user-images.githubusercontent.com/7436127/69601347-a96c9c80-1035-11ea-8ce6-1245fdcdbf06.png)

Defense = 2, Damage: 24 — 36 (~ 30)
![image](https://user-images.githubusercontent.com/7436127/69601371-bf7a5d00-1035-11ea-81fe-948de0017f69.png)

Defense = 3, Damage: 23 — 58 (~ 40)
![image](https://user-images.githubusercontent.com/7436127/69601389-d6b94a80-1035-11ea-93c1-c986ae2bc973.png)

**Comment by rudnovd** [comment]
Спасибо за найденную ошибку.
Исправлено в [9405980](https://github.com/rudnovd/heroes3-damage-calculator/commit/9405980b0e869a868b3223568e2e8acd3ca2fea7#diff-986c4374f9bf19e9968279cd27621fb4R335).
